services:
    phlexible_gui.asset.resource_finder:
        class: Phlexible\Component\Bundler\Finder\ResourceFinder
        public: false
        arguments:
            - "@puli.discovery"

    phlexible_gui.asset.line_separator_content_filter:
        class: Phlexible\Component\Bundler\Filter\LineSeparatorContentFilter
        arguments:
            - "\n"

    phlexible_gui.asset.ensure_trailing_separator_content_filter:
        class: Phlexible\Component\Bundler\Filter\EnsureTrailingSeparatorContentFilter
        arguments:
            - "\n"

    phlexible_gui.asset.base_url_content_filter:
        class: Phlexible\Component\Bundler\Filter\BaseUrlContentFilter
        arguments:
            - ""
            - ""

    phlexible_gui.asset.js_content_filter:
        class: Phlexible\Component\Bundler\Filter\ChainContentFilter
        arguments:
            -
                - "@phlexible_gui.asset.line_separator_content_filter"
                - "@phlexible_gui.asset.ensure_trailing_separator_content_filter"

    phlexible_gui.asset.css_content_filter:
        class: Phlexible\Component\Bundler\Filter\ChainContentFilter
        arguments:
            -
                - "@phlexible_gui.asset.js_content_filter"
                - "@phlexible_gui.asset.base_url_content_filter"

    phlexible_gui.asset.js_mapped_content_builder:
        class: Phlexible\Component\Bundler\ContentBuilder\MappedContentBuilder
        public: false
        arguments:
            - "@phlexible_gui.asset.js_content_filter"

    phlexible_gui.asset.css_mapped_content_builder:
        class: Phlexible\Component\Bundler\ContentBuilder\MappedContentBuilder
        public: false
        arguments:
            - "@phlexible_gui.asset.css_content_filter"

    phlexible_gui.asset.require_script_resource_resolver:
        class: Phlexible\Component\Bundler\ResourceResolver\RequireScriptResourceResolver
        public: false

    phlexible_gui.asset.add_all_resource_resolver:
        class: Phlexible\Component\Bundler\ResourceResolver\AddAllResourceResolver
        public: false

    phlexible_gui.asset.namespace_translation_extractor:
        class: Phlexible\Component\Bundler\Translation\NamespaceTranslationExtractor
        public: false

    phlexible_gui.asset.namespace_translation_builder:
        class: Phlexible\Component\Bundler\Translation\NamespaceTranslationBuilder
        public: false

    phlexible_gui.asset.scripts_builder:
        class: Phlexible\Bundle\GuiBundle\Asset\ScriptsBuilder
        arguments:
            - "@phlexible_gui.asset.resource_finder"
            - "@phlexible_gui.asset.require_script_resource_resolver"
            - "@phlexible_gui.asset.js_mapped_content_builder"
            - "@phlexible_gui.compressor.javascript"
            - "%phlexible_gui.asset_cache_dir%"
            - "%kernel.debug%"

    phlexible_gui.asset.css_builder:
        class: Phlexible\Bundle\GuiBundle\Asset\CssBuilder
        arguments:
            - "@phlexible_gui.asset.resource_finder"
            - "@phlexible_gui.asset.add_all_resource_resolver"
            - "@phlexible_gui.asset.css_mapped_content_builder"
            - "@phlexible_gui.compressor.css"
            - "%phlexible_gui.asset_cache_dir%"
            - "%kernel.debug%"

    phlexible_gui.asset.icons_builder:
        class: Phlexible\Bundle\GuiBundle\Asset\IconsBuilder
        arguments:
            - "@phlexible_gui.asset.resource_finder"
            - "@phlexible_gui.compressor.css"
            - "%phlexible_gui.asset_cache_dir%"
            - "%kernel.debug%"

    phlexible_gui.asset.translations_builder:
        class: Phlexible\Bundle\GuiBundle\Asset\TranslationsBuilder
        arguments:
            - "@translator"
            - "@phlexible_gui.asset.namespace_translation_extractor"
            - "@phlexible_gui.asset.namespace_translation_builder"
            - "@phlexible_gui.compressor.javascript"
            - "%phlexible_gui.asset_cache_dir%"
            - "%locale%"
            - "%kernel.debug%"
