parameters:
    asset.cache_dir: %kernel.cache_dir%/assets/

services:
    phlexible_gui.asset.resource_finder:
        class: Phlexible\Bundle\GuiBundle\Asset\Finder\ResourceFinder
        public: false
        arguments:
            - "@puli.discovery"

    phlexible_gui.asset.builder.mapped_content_builder:
        class: Phlexible\Bundle\GuiBundle\Asset\MappedContent\MappedContentBuilder
        public: false

    phlexible_gui.asset.builder.scripts_resource_resolver:
        class: Phlexible\Bundle\GuiBundle\Asset\ResourceResolver\ScriptsResourceResolver
        public: false

    phlexible_gui.asset.builder.scripts:
        class: Phlexible\Bundle\GuiBundle\Asset\Builder\ScriptsBuilder
        arguments:
            - "@phlexible_gui.asset.resource_finder"
            - "@phlexible_gui.asset.builder.scripts_resource_resolver"
            - "@phlexible_gui.asset.builder.mapped_content_builder"
            - "@phlexible_gui.compressor.javascript"
            - "%asset.cache_dir%"
            - "%kernel.debug%"

    phlexible_gui.asset.builder.css:
        class: Phlexible\Bundle\GuiBundle\Asset\Builder\CssBuilder
        arguments:
            - "@phlexible_gui.asset.resource_finder"
            - "@phlexible_gui.asset.builder.mapped_content_builder"
            - "@phlexible_gui.compressor.css"
            - "%asset.cache_dir%"
            - "%kernel.debug%"

    phlexible_gui.asset.builder.icons:
        class: Phlexible\Bundle\GuiBundle\Asset\Builder\IconsBuilder
        arguments:
            - "@phlexible_gui.asset.resource_finder"
            - "@phlexible_gui.compressor.css"
            - "%asset.cache_dir%"
            - "%kernel.debug%"

    phlexible_gui.asset.builder.translations:
        class: Phlexible\Bundle\GuiBundle\Asset\Builder\TranslationsBuilder
        arguments:
            - "@translator"
            - "@phlexible_gui.compressor.javascript"
            - "%asset.cache_dir%"
